packages:
  - vue2-playground
  - vue3-playground
  - vue2.7-playground
  - demo
  - common

allowBuilds:
  '@parcel/watcher': false
  core-js: true
  esbuild: true
  unrs-resolver: false
  vue-demi: true

packageExtensions:
  vue-template-compiler:
    peerDependencies:
      vue: ~2.6.14
